#!/bin/bash
# -*- sh-basic-offset: 2; indent-tabs-mode: nil -*-

declare -A dirs=()
for i in "$@"
do
  i="${i%/}"
  dirs["$i"]=yes
  while n="${i%/*}"
        [ "$n" != "$i" ]
  do
    i="$n"
    dirs["$i"]=yes
  done
done
[ "${#dirs[@]}" -gt 0 ] && printf '%s\n' "${!dirs[@]}"
