#!/bin/bash

## Copyright (c) 2009-2022, Lancaster University
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are
## met:
##
##  * Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
##
##  * Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the
##    distribution.
##
##  * Neither the name of the copyright holder nor the names of its
##    contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
## A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
## OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
## SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
## LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
## DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
## THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##
## Contributors:
##    Steven Simpson <s.simpson at lancaster.ac.uk>

dir=.

flags=()
while [ $# -gt 0 ]
do
    arg="$1" ; shift
    case "$arg" in
	(--array)
	    vn="$1" ; shift
	    vc="$1" ; shift
	    while [ "$vc" -gt 0 ]
	    do
		eval "$vn"'+=("$1")'
		shift
		vc=$((vc-1))
	    done
	    ;;

	(--)
	    break
	    ;;

	(--out=*)
	    out="${arg#*=}"
	    ;;

	(--dir=*)
	    dir="${arg#*=}"
	    ;;

	(*)
	    flags+=("$arg")
	    ;;
    esac
done

out="$(realpath -mqP "$out")"

#printf >&2 '[%s]\n' "${CD[@]}" "$dir" '&&' "${ZIP[@]}" "$flags" "$out" "$@"
"${CD[@]}" "$dir" && "${ZIP[@]}" "$flags" "$out" "$@"
